language: python
python:
  - "2.7"
  
#https://github.com/BenevolentCoders/rpi-python
#check out this to run a proper virtual environment maybe?
services:
  - docker

before_install:
  - docker pull chukysoria/rpi-python-testing:armv7-py27
  - docker run -d -p 127.0.0.1:80:4567 chukysoria/rpi-python-testing:armv7-py27 /bin/sh -c "cd /root/chukysoria; bundle exec foreman start;"
  - docker ps -a
  - docker run -d chukysoria/rpi-python-testing python -c 'print "Hello World"'

install:
  #normal libraries
  - pip install RPi.GPIO
  
# command to run tests
script: 
  #will fail cuz gpio only on raspi but whatever
  - python GooeyPi.py
