sudo: required

language: python
python:
  - "2.7"
  
#https://github.com/BenevolentCoders/rpi-python
#check out this to run a proper virtual environment maybe?
services:
  - docker

before_install:
  - docker pull docker pull hypriot/rpi-python
  - docker ps -a
  - sudo service docker restart ; sleep 10 #from https://github.com/travis-ci/travis-ci/issues/4778
  - docker run -d --name python hypriot/rpi-python python -c 'print "Hello World"'

install:
  #normal libraries
  - pip install RPi.GPIO
  
# command to run tests
script: 
  #will fail cuz gpio only on raspi but whatever
  - python GooeyPi.py
